// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';

import * as Wsh_XMLHTTP$WshBsTest from "./wsh_XMLHTTP.js";

var req = Wsh_XMLHTTP$WshBsTest.make(/* () */0);

Wsh_XMLHTTP$WshBsTest.open$prime(/* get */5144726, "http://www.example.com", /* None */0, /* None */0, /* None */0, req);

req.onreadystatechange = (function () {
    if (Wsh_XMLHTTP$WshBsTest.ReadyState[/* = */0](req.readyState, Wsh_XMLHTTP$WshBsTest.ReadyState[/* completed */5])) {
      WScript.Echo(req.responseText);
      return /* () */0;
    } else {
      return 0;
    }
  });

Wsh_XMLHTTP$WshBsTest.send(/* None */0, req);

WScript.Echo("Press Enter");

export {
  
}
/* req Not a pure module */
