// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';

import * as Wsh_XMLHTTP from "./wsh_XMLHTTP.js";

var req = Wsh_XMLHTTP.make(/* () */0);

Wsh_XMLHTTP.open$prime(/* get */5144726, "http://www.example.com", /* None */0, /* None */0, /* None */0, req);

req.onreadystatechange = (function () {
    if (req.readyState === Wsh_XMLHTTP.completed) {
      WScript.Echo(req.responseText);
      return /* () */0;
    } else {
      return 0;
    }
  });

req.send();

WScript.Echo("Press Enter");

export {
  
}
/* req Not a pure module */
