// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';


var $$ActiveXObject = 0;

var TextStream = 0;

var WScript = 0;

var XMLHTTP = 0;

export {
  $$ActiveXObject ,
  TextStream      ,
  WScript         ,
  XMLHTTP         ,
  
}
/* No side effect */
