// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';


function writeLine(string, t) {
  if (string) {
    t.WriteLine(string[0]);
    return /* () */0;
  } else {
    t.WriteLine();
    return /* () */0;
  }
}

export {
  writeLine ,
  
}
/* No side effect */
