// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';


var Dictionary = 0;

var FileSystemObject = 0;

export {
  Dictionary       ,
  FileSystemObject ,
  
}
/* No side effect */
