// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';

import * as Js_boolean from "bs-platform/lib/es6/js_boolean.js";

function copy($staropt$star, destination, t) {
  var overwrite = $staropt$star ? $staropt$star[0] : /* true */1;
  t.Copy(destination, Js_boolean.to_js_boolean(overwrite));
  return /* () */0;
}

function $$delete($staropt$star, t) {
  var force = $staropt$star ? $staropt$star[0] : /* false */0;
  t.Delete(Js_boolean.to_js_boolean(force));
  return /* () */0;
}

function openAsTextStream($staropt$star, $staropt$star$1, t) {
  var iomode = $staropt$star ? $staropt$star[0] : /* ForReading */-743226525;
  var format = $staropt$star$1 ? $staropt$star$1[0] : /* TristateUseDefault */-716777472;
  return t.OpenAsTextStream((function () {
                  switch (iomode) {
                    case -743226525 : 
                        return 1;
                    case -66432013 : 
                        return 2;
                    case 1027345183 : 
                        return 8;
                    
                  }
                })(), (function () {
                  switch (format) {
                    case -716777472 : 
                        return -2;
                    case 68291476 : 
                        return -1;
                    case -254243171 : 
                        return 0;
                    
                  }
                })());
}

export {
  copy             ,
  $$delete         ,
  openAsTextStream ,
  
}
/* No side effect */
