// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';


function make() {
  return new ActiveXObject("Scripting.Dictionary");
}

var CompareMode = /* module */[
  /* binary */0,
  /* text */1,
  /* database */2
];

export {
  make        ,
  CompareMode ,
  
}
/* No side effect */
