// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';

import * as Caml_obj   from "bs-platform/lib/es6/caml_obj.js";
import * as Js_boolean from "bs-platform/lib/es6/js_boolean.js";

function make() {
  return new ActiveXObject("MSXML2.XMLHTTP");
}

function open$prime(meth, url, $staropt$star, $staropt$star$1, $staropt$star$2, t) {
  var async = $staropt$star ? $staropt$star[0] : /* true */1;
  var user = $staropt$star$1 ? $staropt$star$1[0] : "";
  var password = $staropt$star$2 ? $staropt$star$2[0] : "";
  t.open((function () {
            switch (meth) {
              case 5144726 : 
                  return "get";
              case -899906464 : 
                  return "post";
              case 5595855 : 
                  return "put";
              
            }
          })(), url, Js_boolean.to_js_boolean(async), user, password);
  return /* () */0;
}

function send(body, t) {
  if (body) {
    t.send(body[0][1]);
    return /* () */0;
  } else {
    t.send();
    return /* () */0;
  }
}

var $eq = Caml_obj.caml_equal;

var ReadyState = /* module */[
  /* = */$eq,
  /* uninitialized */0,
  /* loading */1,
  /* loaded */2,
  /* interactive */3,
  /* completed */4
];

var $eq$1 = Caml_obj.caml_equal;

var Status = /* module */[
  /* = */$eq$1,
  /* continue */100,
  /* switching_protocols */101,
  /* ok */200,
  /* created */201,
  /* accepted */202,
  /* non_authoritative_info */203,
  /* no_content */204,
  /* reset_content */205,
  /* partial_content */206,
  /* multiple_choices */300,
  /* moved_permanently */301,
  /* found */302,
  /* see_other */303,
  /* not_modified */304,
  /* use_proxy */305,
  /* temporary_redirect */307,
  /* bad_request */400,
  /* unauthorized */401,
  /* payment_required */402,
  /* forbidden */403,
  /* not_found */404,
  /* method_not_allowed */405,
  /* not_acceptable */406,
  /* proxy_auth_required */407,
  /* req_timeout */408,
  /* conflict */409,
  /* gone */410,
  /* length_required */411,
  /* precondition_failed */412,
  /* req_entity_too_large */413,
  /* req_uri_too_long */414,
  /* unsupported_media_type */415,
  /* requested_range_not_suitable */416,
  /* expectation_failed */417,
  /* internal_server_error */500,
  /* not_implemented */501,
  /* bad_gateway */502,
  /* service_unavailable */503,
  /* gateway_timeout */504,
  /* http_version_not_supported */505
];

export {
  make       ,
  open$prime ,
  send       ,
  ReadyState ,
  Status     ,
  
}
/* No side effect */
