// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';

import * as Js_boolean from "bs-platform/lib/es6/js_boolean.js";

function make() {
  return new ActiveXObject("MSXML2.XMLHTTP");
}

function open$prime(meth, url, $staropt$star, $staropt$star$1, $staropt$star$2, t) {
  var async = $staropt$star ? $staropt$star[0] : /* true */1;
  var user = $staropt$star$1 ? $staropt$star$1[0] : "";
  var password = $staropt$star$2 ? $staropt$star$2[0] : "";
  t.open((function () {
            switch (meth) {
              case 5144726 : 
                  return "get";
              case -899906464 : 
                  return "post";
              case 5595855 : 
                  return "put";
              
            }
          })(), url, Js_boolean.to_js_boolean(async), user, password);
  return /* () */0;
}

function send(body, t) {
  if (body) {
    t.send(body[0][1]);
    return /* () */0;
  } else {
    t.send();
    return /* () */0;
  }
}

var uninitialized = 0;

var loading = 1;

var loaded = 2;

var interactive = 3;

var completed = 4;

export {
  make          ,
  open$prime    ,
  send          ,
  uninitialized ,
  loading       ,
  loaded        ,
  interactive   ,
  completed     ,
  
}
/* No side effect */
