// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';


function make() {
  return new ActiveXObject("MSXML2.XMLHTTP");
}

function open$prime(meth, url, $staropt$star, $staropt$star$1, $staropt$star$2, t) {
  var async = $staropt$star ? $staropt$star[0] : /* true */1;
  var user = $staropt$star$1 ? $staropt$star$1[0] : "";
  var password = $staropt$star$2 ? $staropt$star$2[0] : "";
  t.open((function () {
            switch (meth) {
              case 5144726 : 
                  return "get";
              case -899906464 : 
                  return "post";
              case 5595855 : 
                  return "put";
              
            }
          })(), url, async, user, password);
  return /* () */0;
}

var uninitialized = 0;

var loading = 1;

var loaded = 2;

var interactive = 3;

var completed = 4;

export {
  make          ,
  open$prime    ,
  uninitialized ,
  loading       ,
  loaded        ,
  interactive   ,
  completed     ,
  
}
/* No side effect */
