// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';


function make() {
  return new ActiveXObject("Scripting.FileSystemObject");
}

function openTextFile(filename, $staropt$star, $staropt$star$1, $staropt$star$2, t) {
  var iomode = $staropt$star ? $staropt$star[0] : /* ForReading */-743226525;
  var create = $staropt$star$1 ? $staropt$star$1[0] : /* false */0;
  var format = $staropt$star$2 ? $staropt$star$2[0] : /* TristateUseDefault */-716777472;
  return t.OpenTextFile(filename, (function () {
                  switch (iomode) {
                    case -743226525 : 
                        return 1;
                    case -66432013 : 
                        return 2;
                    case 1027345183 : 
                        return 8;
                    
                  }
                })(), create, (function () {
                  switch (format) {
                    case -716777472 : 
                        return -2;
                    case 68291476 : 
                        return -1;
                    case -254243171 : 
                        return 0;
                    
                  }
                })());
}

export {
  make         ,
  openTextFile ,
  
}
/* No side effect */
