// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Xml_http_req = require("./xml_http_req.js");

var req = Xml_http_req.make(/* () */0);

req.open("get", "http://www.example.com");

req.onreadystatechange = (function () {
    if (req.readyState === Xml_http_req.completed) {
      WScript.Echo(req.responseText);
      return /* () */0;
    } else {
      return 0;
    }
  });

req.send();

WScript.Echo("Press Enter");

/* req Not a pure module */
