// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';


function make() {
  return new ActiveXObject("MSXML2.XMLHTTP");
}

var uninitialized = 0;

var loading = 1;

var loaded = 2;

var interactive = 3;

var completed = 4;

exports.make          = make;
exports.uninitialized = uninitialized;
exports.loading       = loading;
exports.loaded        = loaded;
exports.interactive   = interactive;
exports.completed     = completed;
/* No side effect */
